### ISSUE TITLE
Support for RSA

### ISSUE THREAD

**Issue by F21** [luciferous/jwt#2]
Could you add support for RSA (public/private keys)?

We can then give the client a private key to sign their requests (we do not store the private key on our server at all).

Then when we receive it, we can decrypt the signature with the public key to see if the contents were tampered with.

**Comment by luciferous** [comment]
Hi, could you provide more details about you're looking for?

**Comment by F21** [comment]
Hi there :)

I am basically looking at public/private keys to sign the signature like google: https://developers.google.com/accounts/docs/OAuth2ServiceAccount

Out of band, we generate a pub/priv key pair and give the private key to the client. The client then signs his request with the private key.

On our end, we decrypt the signature with the public key to see if the contents matches the payload.

Cheers :)

**Comment by luciferous** [comment]
I'm not sure if that's part of JWT. Could you provide an example of another JWT library that does this?

**Comment by luciferous** [comment]
Hi @F21, I think I see what you mean. Would it be enough to abstract over the signing function? Currently, `JWT::encode` calls `JWT::sign` with the message key and signing algorithm obtaining a signature:

```
$signature = JWT::sign($signing_input, $key, $algo);
```

If `JWT::encode` could be passed a function instead, you could define arbitrary signing implementations, for e.g. something like the following:

```
$rsa = new Crypt_RSA();
$rsa->loadKey('...'); // public key
//$rsa->setEncryptionMode(CRYPT_RSA_ENCRYPTION_OAEP);
$payload = '...';
$ciphertext = JWT::encode($payload, array($rsa, 'encrypt'));
```

Would that work for you?

**Comment by F21** [comment]
@luciferous:

I ended up implementing my own JWT library (based on yours and Google's PHP SDK) a while back: https://github.com/F21/jwt

My apologies for not closing this issue.

Your implementation should also work very well. I like how it allows you to define arbitrary singing implementations :)

**Comment by luciferous** [comment]
@F21:

Ah, ok. Fantastic. Sorry for my late reply, I'm glad you got it working for yourself. I'll keep this issue open to remind myself to factor out the signing function like I described above, and then plug in hmac and openssl to support the current suite as well as RSA.
